apiVersion: v1
kind: Service
metadata:
  name: poc-service
  namespace: poc-namespace
  labels:
    app: poc-app
spec:
  selector:
    app: poc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deployment
  namespace: poc-namespace
  labels:
    app: poc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
